### ISSUE TITLE
Форматирование текстовых сообщений

### ISSUE THREAD

**Issue by EvgeniySerikov** [platforma-pw/main#1]
А можно сделать так, чтобы на платформе была возможность форматирования текстовых сообщений, которые отправляет бот? Например, делать заголовок, подзаголовок, жирный шрифт, добавлять картинку..

**Comment by nickvorobiov** [comment]
пока не делаем, потому что это умеет телеграм, но не умеет фейсбук, а у нас сейчас фб основной, так что смысла не очень много
