### ISSUE TITLE
Таймаут

### ISSUE THREAD

**Issue by EvgeniySerikov** [platforma-pw/main#3]
Сейчас таймаут отправки сообщений отсчитывается от входа в стадию. Было бы удобней, если бы таймаут считался от предыдущего шага данной стадии.

Например, Стадия 2, вход в стадию - переход на страницу. Через 20 минут отправляется сообщение "Выгода 1". Через 20 минут после отправки сообщения "Выгода 1" отправляется сообщение "Выгода 2". Сейчас, чтобы это условие соблюдалось второй таймаут нужно выбирать 40 минут (20+20), но так не очень удобно плюсовать каждый таймаут.

**Comment by nickvorobiov** [comment]
Всё, что происходит в стадии, считается от старта стадии. В этом основная идея стадий. Зато можно чётко и сразу без складывания в уме понять, сколько максимум времени человек тусит в стадии, прежде чем перекидывать его дальше.
