### ISSUE TITLE
Выпадающий список созданных страниц

### ISSUE THREAD

**Issue by EvgeniySerikov** [platforma-pw/main#4]
Когда я добавляю сообщение в стадию, мне платформа предлагает сделать в этом сообщении кнопку с внешней ссылкой или со ссылкой на страницу. Сейчас непонятно где эти созданные страницы и как их привязать к этой кнопке.

Предлагаю сделать так: я добавляю сообщение и выбираю кнопку со ссылкой на страницу. Мне платформа предлагает выпадающий список с уже созданными страницами и кнопочкой "Создать новую страницу". Если пока не создано ни одной страницы, на месте выпадающего списка только кнопка "Создать новую страницу".

**Comment by nickvorobiov** [comment]
У каждой страницы теперь есть нормальный адрес, и эти адреса видно в админке
