### ISSUE TITLE
Функции кнопки на странице

### ISSUE THREAD

**Issue by EvgeniySerikov** [platforma-pw/main#6]
Чтобы упростить создание воронки предлагаю добавить к функциям кнопки на лендинге отправку сообщений. Сейчас, если я создаю на платформе страницу, я могу указать текст кнопки и урл этой кнопки. А если я хочу, чтобы по нажатию на кнопку человеку отправлялось сообщение в мессенджер со ссылкой на скачивание файла?

Я так понял, что сейчас это реализуется с помощью функции переадресация? Это сложно. Предлагаю в окне создания страницы к функциям кнопки добавить "Отправить сообщение". Т.е. я создал страницу с кнопкой и платформа мне предлагает 1) Кнопка, ведущая на уже созданную мной страницу; 2) Кнопка с внешней ссылкой; 3) Кнопка, по нажатию на которую отправляется сообщение (либо уже созданное, либо предлагается создать это сообщение).

Или чтобы платформа предлагала выпадающий список из действий, которые произойдут после нажатия на кнопку: 1) Открыть страницу такую-то (список уже созданных страниц и кнопка "Создать новую страницу"); 2) Открыть внешнюю ссылку; 3) Отправить сообщение (список уже созданных сообщений и кнопка "создать новое сообщение").

**Comment by nickvorobiov** [comment]
Для этого предназначен тип кнопки «команда боту» и стадия с типом «команда боту».
